server:
  port: 8080

logging:
  level:
    ROOT: info
    org.springframework.security: debug
    org.springframework.web: debug
    org.grs.generator.mapper: debug
    org.springframework.beans.factory.annotation: debug

spring:
  resources:
    chain:
      enabled: true
  application:
    name: generator
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/generator?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    jdbcUrl: jdbc:mysql://localhost:3306/generator?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: gen_user
    password: gen_pass
  jackson:
    serialization-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  executor-type: reuse
  configuration:
#    cacheEnabled: false
#    lazyLoadingEnabled: true
#    aggressiveLazyLoading: false
    useGeneratedKeys: true
#    lazyLoadTriggerMethods: none

