server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.grs.generator.mapper: DEBUG

spring:
  resources:
    chain:
      enabled: true
  application:
    name: cruncher
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/generator?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: gen_user
    password: gen_pass
  jackson:
    serialization-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


