server:
  port: ${web.server.port:8080}

logging:
  level:
    ROOT: info
    org.springframework.security: debug
    org.springframework.web.servlet: debug
    org.grs.generator.mapper: debug
    org.springframework.beans.factory.annotation: debug
    com.zaxxer.hikari.HikariConfig: debug
#    com.zaxxer.hikari.pool: debug

spring:
  resources:
    chain:
      enabled: true
      html-application-cache: false
      cache: false
  application:
    name: generator
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${jdbc.host:localhost}:${jdbc.port:3306}/generator?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&useSSL=false
    username: ${jdbc.username:gen_user}
    password: ${jdbc.password:gen_pass}
    hikari:
      jdbc-url: ${spring.datasource.url}
  hazelcast:
    config: hazelcast.xml

mybatis:
  executor-type: reuse
  configuration:
#    cacheEnabled: false
#    lazyLoadingEnabled: true
#    aggressiveLazyLoading: false
    useGeneratedKeys: true
#    lazyLoadTriggerMethods: none

---
#spring:
#  profiles: test
#server:
#  port: 8088

