server:
  port: ${web.server.port:8080}

logging:
  level:
    ROOT: info
    org.springframework.security: debug
    org.springframework.web.servlet: debug
    org.grs.generator.mapper: debug
    org.springframework.beans.factory.annotation: debug
    com.zaxxer.hikari.HikariConfig: debug
#    com.zaxxer.hikari.pool: debug

spring:
  application:
    name: generator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:mysql://${jdbc.host:localhost}:${jdbc.port:3306}/generator\
      ?autoReconnect=true&useUnicode=true&characterEncoding=utf-8\
      &zeroDateTimeBehavior=convertToNull&allowMultiQueries=true\
      &useSSL=false&allowPublicKeyRetrieval=true"
    username: ${jdbc.username:gen_user}
    password: ${jdbc.password:gen_pass}
    hikari:
      jdbc-url: ${spring.datasource.url}
  resources:
    chain:
      enabled: true
      html-application-cache: false
      cache: false

doyto:
  query:
    config:
      map-camel-case-to-underscore: false
